### ISSUE TITLE
`id_token code` not supported

### ISSUE THREAD

**Issue by brunokrebs** [auth0/express-openid-client#2]
The following example generates an error saying that `id_token code` is not supported. Then, I found out that `code id_token` is what the library (or something else?) is expecting. Is this by design? Or room for improvement?

```js
app.use(eoc.routes({
  issuer_base_url: process.env.AUTH0_DOMAIN,
  client_id: process.env.AUTH0_CLIENT_ID,
  client_secret: process.env.AUTH0_CLIENT_SECRET,
  base_url: appUrl,
  authorizationParams: {
    response_type: 'id_token code',
  },
}));
```

**Comment by jfromaniello** [comment]
the order was wrong, it should be `code id_token` instead

**Comment by brunokrebs** [comment]
Thanks, but that was exactly the question. Should the library force the order?

**Comment by ecs-hk** [comment]
@brunokrebs I know the issue is closed, but I just want to mention to you:

https://openid.net/specs/openid-connect-core-1_0.html

"code id_token" is part of the spec (for Hybrid Flow), and "id_token code" does not have any meaning in the context of response types. So, yes, this is by design.
